namespace Kroki;

public static class DiagramTypes
{
    public const string
        BlockDiag = "blockdiag",
        Bpmn = "bpmn",
        Bytefield = "bytefield",
        SeqDiag = "seqdiag",
        ActDiag = "actdiag",
        NwDiag = "nwdiag",
        PacketDiag = "packetdiag",
        RackDiag = "rackdiag",
        C4PlantUml = "c4plantuml",
        D2 = "d2",
        Dbml = "dbml",
        Ditaa = "ditaa",
        Erd = "erd",
        Excalidraw = "excalidraw",
        GraphViz = "graphviz",
        Mermaid = "mermaid",
        Nomnoml = "nomnoml",
        Pikchr = "pikchr",
        PlantUml = "plantuml",
        Structurizr = "structurizr",
        Svgbob = "svgbob",
        Symbolator = "symbolator",
        TikZ = "tikz",
        Umlet = "umlet",
        Vega = "vega",
        VegaLite = "vegalite",
        WaveDrom = "wavedrom",
        WireViz = "wireviz"
        ;
    public static ReadOnlySpan<string> All => all;
    private static readonly string[] all =
    [
        BlockDiag,
        Bpmn,
        Bytefield,
        SeqDiag,
        ActDiag,
        NwDiag,
        PacketDiag,
        RackDiag,
        C4PlantUml,
        D2,
        Dbml,
        Ditaa,
        Erd,
        Excalidraw,
        GraphViz,
        Mermaid,
        Nomnoml,
        Pikchr,
        PlantUml,
        Structurizr,
        Svgbob,
        Symbolator,
        TikZ,
        Umlet,
        Vega,
        VegaLite,
        WaveDrom,
        WireViz,
    ];
}